server:
  port: 9004

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SurendarVarma555/collections-common-config.git
          clone-on-start: true